name = "StarSoul SMP"
author = "SKY-LESS"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acb4e81c8f1781b9dd61c1235687449708108f1cabc71f2b1f1caf84cf646434"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
