name = "StarSoul SMP"
author = "SKY-LESS"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5916e1c4d304977bdbf46a3c860bc9f6302fa6da1bcbb4ab5323a5770c452729"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
