name = "StarSoul SMP"
author = "SKY-LESS"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3319097801766e30f2594e205dd62872f7b52e3d1f798b0b37875ae6f57bc9b3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
